name: Process Soil Data

on:
  push:
    branches:
      - main

jobs:
  update_soil_data:
    name: Update Soil Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgdal-dev gdal-bin
          pip install numpy
          pip install GDAL
          pip install dvc[gdrive]
      
      - name: Download and Process Data
        run: |
          wget -O soil_data.zip "https://databasin2-filestore.s3.amazonaws.com/a4cb6d367eae4e52a08902874f8bfedf/download/a4cb6d367eae4e52a08902874f8bfedf_1_zip_en.zip?Signature=ne2Aa6KK3wnmbjRWPPNV0TTecMw%3D&Expires=1679157927&AWSAccessKeyId=AKIAI4RK5BEPK3FCQPUQ"
          unzip -o soil_data.zip -d Data/Soil
          cd Data/Soil
          python process.py
          gdalwarp -to SRC_METHOD=NO_GEOTRANSFORM -s_srs EPSG:4326 -t_srs EPSG:4326 -tr 0.5 0.5 -r near -te -180.0 -90.0 180.0 90.0 -te_srs EPSG:4326 -of GTiff soilcarbon.ovr GlobalSoilOrganicCarbonDensityinkgCarbon_m2to1meterdepth.tif
      
      - name: Commit and Push Changes
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          cd Data/Soil
          dvc add GlobalSoilOrganicCarbonDensityinkgCarbon_m2to1meterdepth.tif

