name: Capture and Preprocess data
on:
  schedule:
    - cron: '1 * * * *'
  workflow_dispatch:
  
  
jobs:
  update_data:
    name: Update Data from source
    runs-on: ubuntu-latest
    steps:
         - name: Checkout
           uses: actions/checkout@v2
         - name: Setup Python
           uses: actions/setup-python@v2
           with:
             python-version: '3.8'
             cache: 'pip'
         - name: Install Dependencies
           run: |
            sudo add-apt-repository ppa:ubuntugis/ppa && sudo apt-get update
            sudo apt-get install gdal-bin
            sudo apt-get install libgdal-dev
            export CPLUS_INCLUDE_PATH=/usr/include/gdal
            export C_INCLUDE_PATH=/usr/include/gdal
            pip install wheel
            pip install numpy
            sudo pip3 install GDAL==$(gdal-config --version | awk -F'[.]' '{print $1"."$2}') --global-option=build_ext --global-option="-I/usr/include/gdal"
            pip install ipython
            pip install dvc[gdrive]
         - name: Run Script
           run: |
            cd Data/Soil/
            pip install wget
            wget --auth-no-challenge --user=imajinarts14 --password=junior$$14 "https://databasin2-filestore.s3.amazonaws.com/a4cb6d367eae4e52a08902874f8bfedf/download/a4cb6d367eae4e52a08902874f8bfedf_1_zip_en.zip?Signature=ne2Aa6KK3wnmbjRWPPNV0TTecMw%3D&Expires=1679157927&AWSAccessKeyId=AKIAI4RK5BEPK3FCQPUQ"
            python process.py
            gdalwarp -to SRC_METHOD=NO_GEOTRANSFORM -s_srs EPSG:4326 -t_srs EPSG:4326 -tr 0.5 0.5 -r near -te -180.0 -90.0 180.0 90.0 -te_srs EPSG:4326 -of GTiff "data/commonData\Data0\soilcarbon.ovr" GlobalSoilOrganicCarbonDensityinkgCarbon_m2to1meterdepth.tif
         - name: Commit and Push Changes
           env:
            GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
           run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions"
            dvc add Data/Soil/GlobalSoilOrganicCarbonDensityinkgCarbon_m2to1meterdepth.tif
            git add Data/Soil/GlobalSoilOrganicCarbonDensityinkgCarbon_m2to1meterdepth.tif.dvc 
            git add Data/Soil/process.py
            git commit -m "Updated dataset on `date` with GitHub Actions"
            git push origin task-three
            dvc push
