name: Capture and Preprocess data
on:
  schedule:
    - cron: '1 * * * *'
  workflow_dispatch:
  
  
jobs:
  update_data:
    name: Update Data from source
    runs-on: ubuntu-latest
    steps:
         - name: Checkout
           uses: actions/checkout@v2
         - name: Setup Python
           uses: actions/setup-python@v2
           with:
             python-version: '3.8'
             cache: 'pip'
         - name: Install Dependencies
           run: |
            sudo add-apt-repository ppa:ubuntugis/ppa && sudo apt-get update
            sudo apt-get install gdal-bin
            sudo apt-get install libgdal-dev
            export CPLUS_INCLUDE_PATH=/usr/include/gdal
            export C_INCLUDE_PATH=/usr/include/gdal
            pip install wheel
            pip install numpy
            sudo pip3 install GDAL==$(gdal-config --version | awk -F'[.]' '{print $1"."$2}') --global-option=build_ext --global-option="-I/usr/include/gdal"
            pip install ipython
            pip install dvc[gdrive]
         - name: Run Script
           run: |
            cd Data/LandCover/
            pip install wget
            python process.py
            gdalwarp -co COMPRESS=DEFLATE -co PREDICTOR=2 -co ZLEVEL=9 -t_srs EPSG:4326 -tr 0.01 0.01 -r near -te -180.0 -90.0 180.0 90.0 -te_srs EPSG:4326 -of GTiff FML_v3-2_with-colorbar.tif GlobalForestManagementData_at_a_100m_resolution.tif
         - name: Commit and Push Changes
           env:
            GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
           run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions"
            dvc add Data/LandCover/GlobalForestManagementData_at_a_100m_resolution.tif
            git add Data/LandCover/GlobalForestManagementData_at_a_100m_resolution.tif.dvc 
            git add Data/LandCover/process.py
            git commit -m "Updated dataset on `date` with GitHub Actions"
            git push origin task-four
            dvc push
