name: Capture and Preprocess data
on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:
  
  
jobs:
  update_data:
    name: Update Data from source
    runs-on: ubuntu-latest
    steps:
         - name: Checkout
           uses: actions/checkout@v2
         - name: Setup Python
           uses: actions/setup-python@v2
           with:
             python-version: '3.8'
             cache: 'pip'
         - name: Install Dependencies
           run: |
            sudo add-apt-repository ppa:ubuntugis/ppa && sudo apt-get update
            sudo apt-get install gdal-bin
            sudo apt-get install libgdal-dev
            export CPLUS_INCLUDE_PATH=/usr/include/gdal
            export C_INCLUDE_PATH=/usr/include/gdal
            pip install wheel
            pip install numpy
            sudo pip3 install GDAL==$(gdal-config --version | awk -F'[.]' '{print $1"."$2}') --global-option=build_ext --global-option="-I/usr/include/gdal"
            sudo apt-get install qgis
            pip install ipython
            pip install dvc[gdrive]
         - name: Run Script
           run: |
            cd Data/Climate/
            pip install wget
            python process.py
         - name: Commit and Push Changes
           env:
            GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
           run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions"
            dvc add Data/Climate/IPCC_ClimateZoneMap.tif
            git add Data/Climate/IPCC_ClimateZoneMap.tif.dvc
            dvc add Data/Climate/IPCC_ClimateZoneMap.geojson
            git add Data/Climate/IPCC_ClimateZoneMap.geojson.dvc
            git add Data/Climate/process.py
            git add Data/Climate/curate.py
            git commit -m "Updated dataset on `date` with GitHub Actions"
            git config pull.rebase true
            git pull
            git push origin master
            dvc pull
            dvc push
            python curate.py