name: Capture and Preprocess data
on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:


jobs:
  update_data:
    name: Update Data from source
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install Dependencies
        run: |
          pip install wheel
          pip install numpy
          pip install ipython
          pip install dvc[gdrive]
      - name: Run Script
        run: |
          cd Data/EcoRegion/
          python -m pip install wget
          python preprocess.py
      - name: Commit and Push Changes
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          dvc add Data/EcoRegion/terrestrial_ecosystems.tif
          git add Data/EcoRegion/terrestrial_ecosystems.tif.dvc 
          git add Data/EcoRegion/preprocess.py
          git commit -m "Updated dataset on $(date) with GitHub Actions"
          git config pull.rebase true
          git pull
          git push origin master
          dvc pull
          dvc push
